services:
  app:
    image: itemglow:latest
    container_name: itemglow_app
    ports:
      - "6660:7860"
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

networks:
  default:
    driver: bridge