FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04

# 設定工作目錄
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.12 \
    python3-pip \
    libgl1 \
    libglib2.0-0 \
    cmake \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 升級 pip
RUN pip3 install --no-cache-dir --upgrade pip

# 複製需要的檔案
COPY . .

# 安裝 Python 套件
RUN pip3 install --no-cache-dir -r requirements.txt

# 容器啟動指令
CMD ["python3", "webui.py"]