FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04

# 設定工作目錄
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.12 \
    python3-pip \
    python3-venv \
    libgl1 \
    libglib2.0-0 \
    cmake \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 複製需要的檔案
COPY . .

# 建立虛擬環境
RUN python3 -m venv /app/venv

# 啟用虛擬環境並安裝 Python 套件
RUN /app/venv/bin/pip install --no-cache-dir -r requirements.txt

# 容器啟動指令
CMD ["/app/venv/bin/python", "webui.py"]